name: A Quiet Landscape
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#343432'
    - '#62645e'
    - '#7d7972'
    - '#bfb28f'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.4519103979691863
purpose: []
