name: A Quiet Landscape
favicon: null
layout_spectrum: 0.7727185683324933
typography_spectrum: 0.8668437704909593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9196855502668768
  lightness: 0.5129335457459092
  saturation: 0.9202406099066138
  rhythmicContrast: 0.4519103979691863
purpose: []
